# Generated by Django 2.1.3 on 2019-01-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mssql', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backuphistory',
            fields=[
                ('backuphistid', models.AutoField(db_column='BackupHistId', primary_key=True, serialize=False)),
                ('fullbackupdate', models.DateTimeField(blank=True, db_column='FullbackupDate', null=True)),
                ('diffbackupdate', models.DateTimeField(blank=True, db_column='DiffBackupDate', null=True)),
                ('tranbackupdate', models.DateTimeField(blank=True, db_column='TranBackupDate', null=True)),
                ('fullbackupsize', models.DecimalField(blank=True, db_column='FullBackupSize', decimal_places=0, max_digits=20, null=True)),
                ('diffbackupsize', models.DecimalField(blank=True, db_column='DiffBackupSize', decimal_places=0, max_digits=20, null=True)),
                ('tranbackupsize', models.DecimalField(blank=True, db_column='TranBackupSize', decimal_places=0, max_digits=20, null=True)),
                ('fullbackupduration', models.IntegerField(blank=True, db_column='FullBackupDuration', null=True)),
                ('diffbackupduration', models.IntegerField(blank=True, db_column='DiffBackupDuration', null=True)),
                ('tranbackupduration', models.IntegerField(blank=True, db_column='TranBackupDuration', null=True)),
                ('compressed', models.BooleanField(blank=True, db_column='Compressed', null=True)),
            ],
            options={
                'db_table': 'BackupHistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Backupschedule',
            fields=[
                ('bkuschedid', models.AutoField(db_column='BkuSchedId', primary_key=True, serialize=False)),
                ('timefrom', models.TimeField(blank=True, db_column='TimeFrom', null=True)),
                ('timeto', models.TimeField(blank=True, db_column='TimeTo', null=True)),
            ],
            options={
                'db_table': 'BackupSchedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commandqueue',
            fields=[
                ('guid', models.CharField(db_column='GUID', max_length=254)),
                ('command', models.TextField(db_column='Command')),
                ('jobid', models.CharField(blank=True, db_column='jobId', max_length=50, null=True)),
                ('jobtype', models.CharField(choices=[('BKU', 'BKU'), ('NA', 'Not Available')], db_column='JobType', default='BKU', max_length=20)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('NA', 'Not Available')], db_column='Status', default='Scheduled', max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CommandQueue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('databaseid', models.AutoField(db_column='DatabaseId', primary_key=True, serialize=False)),
                ('databasename', models.CharField(db_column='DatabaseName', max_length=50)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('recoverymodel', models.CharField(blank=True, choices=[('Simple', 'Simple'), ('Bulk-Logged', 'Bulk-Logged'), ('Full', 'Full')], db_column='RecoveryModel', default='Full', max_length=64, null=True)),
                ('currentdbsize', models.CharField(blank=True, db_column='CurrentDBSize', max_length=10, null=True)),
                ('backuppath', models.CharField(blank=True, db_column='BackupPath', max_length=128, null=True)),
            ],
            options={
                'db_table': 'Databases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('logid', models.AutoField(db_column='logId', primary_key=True, serialize=False)),
                ('logmessage', models.TextField(db_column='LogMessage')),
            ],
            options={
                'db_table': 'Logging',
                'managed': False,
            },
        ),
    ]
